### ISSUE TITLE
Add a new user to this REPO for write access

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/fraud-mitigation#25]
Hi, pls add user: parthsandip.mehta@fiserv.com to this GitRepo for Write access as he is one of the Developers of our team actively working.

**Comment by pmehta-finact** [comment]
> Hi, pls add user: [parthsandip.mehta@fiserv.com](mailto:parthsandip.mehta@fiserv.com) to this GitRepo for Write access as he is one of the Developers of our team actively working.

my id: pmehta-finact

**Comment by russnicoletti** [comment]
Hello @pmehta-finact, please let me know which product your team is working on. Thanks.

**Comment by russnicoletti** [comment]
@kongaravinatha The invitation has been sent
