### ISSUE TITLE
Valid Yaml but failing checks as per Validator defined in the Pipeline

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/fraud-mitigation#29]
I have defined an Yaml file at which the Devstudio validator fails when the pipeline is runned. I have verified the validity of the Yaml using the Intellij and Visual Studio code. I didnot understand what went wrong.

https://github.com/Fiserv/fraud-mitigation/actions/runs/10706427216/job/29684127426?pr=28

![image](https://github.com/user-attachments/assets/59dc4e5a-3f07-4861-be89-18152fae8430)

**Comment by russnicoletti** [comment]
The problem was resolved by fixing the indenting in the yaml
