### ISSUE TITLE
Having different Servers for different Paths

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/fraud-mitigation#34]
I have 3 paths in the yaml document. Among the 3 paths, 2 of the paths share common basepath and 1 path will be using another path. 

Example: 
2 paths using the server URL : https://connect-qa.fiservapis.com/fvas-mitigation-v1/
1 path using the server URL : https://connect-uat.fiservapis.com/fvas-enhanced-data/v1/

When I view the CURL command options: 

<img width="1178" alt="image" src="https://github.com/user-attachments/assets/08610dc0-ac13-4430-bc32-7d8839088bb8">

Expected : /send/{clientID} Resource should point to Server URL in CURL command:  https://connect-uat.fiservapis.com/fvas-enhanced-data/v1/

Existing : /send/{clientID} Resource is pointing to Server URL in CURL command:  https://connect-qa.fiservapis.com/fvas-mitigation-v1/

Pls inspect the yaml file. I have placed the server URLs specifically under path sections. But could not achieve this on Devstudio

**Comment by russnicoletti** [comment]
Hi @kongaravinatha, developer studio uses a third-party library to parse and display the API specification information. The third-party library works based on the OpenAPI specification. Dev Studio folks don't have all the information regarding the OpenAPI specification. I encourage you to explore the information available online (google, copilot.microsoft.com, etc) which I'm sure you'll find helpful.
